security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        my_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: my_provider
            form_login:
                login_path: /
                check_path: /
                default_target_path: ticket_index

            logout:
                path: /logout
                target: /
                invalidate_session: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
                -
                    path: ^/dashboard
                    allow_if: "is_granted('ROLE_USER')"

                -
                    path: ^/project
                    allow_if: "is_granted('ROLE_USER')"

                -
                    path: ^/ticket
                    allow_if: "is_granted('ROLE_USER')"
